### ISSUE TITLE
Build error – Actual class/constructor has no corresponding expected declaration (generated Kotlin files)

### ISSUE THREAD

**Issue by Samueljh1** [voize-gmbh/reakt-native-toolkit#29] opened 2023-09-12 10:22 UTC
After following the project setup steps, I tried to build my project after adding the @ReactNativeModule and @ReactNativeMethod annotations (using the example CalculatorRNModule class).

During the build process, the toolkit generates the CalculatorRNModuleProvider.kt file, which then causes the two compilation errors:

- Actual class 'CalculatorRNModuleProvider' has no corresponding expected declaration
- Actual constructor of 'CalculatorRNModuleProvider' has no corresponding expected declaration

The _CalculatorRNModule_ class in my project is defined under commonMain in the shared module.

**Comment by Legion2** [comment] 2023-09-13 07:22
Which Multiplatform targets(Android,iOS,js) are you compiling for?

**Comment by Samueljh1** [comment] 2023-09-13 08:09
> Which Multiplatform targets(Android,iOS,js) are you compiling for?

I am compiling for Android and iOS. The library code works fine when removing the annotations and calling it directly in Swift/Kotlin (i.e., in native code).

**Comment by Legion2** [comment] 2023-09-16 21:58
Have you defined your annotated RN module in common code and added this to you gradle config?
```kotlin
dependencies {
    add("kspCommonMainMetadata", libs.reakt.native.toolkit.ksp)
    add("kspAndroid", libs.reakt.native.toolkit.ksp)
    add("kspIosX64", libs.reakt.native.toolkit.ksp)
    add("kspIosArm64", libs.reakt.native.toolkit.ksp)
}

tasks.withType<org.jetbrains.kotlin.gradle.dsl.KotlinCompile<*>>().configureEach {
    if (name != "kspCommonMainKotlinMetadata") {
        dependsOn("kspCommonMainKotlinMetadata")
    } else {
        finalizedBy("copyGeneratedTypescriptFiles")
    }
}
```

Please check that `CalculatorRNModuleProvider` is generated in the common code (`android/shared/build/generated/ksp/metadata/commonMain/kotlin`) and available in your common code during compilation.

**Comment by boluokvmd** [comment] 2023-10-31 07:07
@Samueljh1 Were you able to resolve this? currently facing the same issue.

**Comment by boluokvmd** [comment] 2023-10-31 10:52
> Have you defined your annotated RN module in common code and added this to you gradle config?
> 
> ```kotlin
> dependencies {
>     add("kspCommonMainMetadata", "de.voize:reakt-native-toolkit-ksp:<version>")
>     add("kspAndroid", "de.voize:reakt-native-toolkit-ksp:<version>")
>     add("kspIosX64", "de.voize:reakt-native-toolkit-ksp:<version>")
>     add("kspIosArm64", "de.voize:reakt-native-toolkit-ksp:<version>")
> }
> 
> tasks.withType<org.jetbrains.kotlin.gradle.dsl.KotlinCompile<*>>().configureEach {
>     if (name != "kspCommonMainKotlinMetadata") {
>         dependsOn("kspCommonMainKotlinMetadata")
>     } else {
>         finalizedBy("copyGeneratedTypescriptFiles")
>     }
> }
> ```
> 
> Please check that `CalculatorRNModuleProvider` is generated in the common code (`android/shared/build/generated/ksp/metadata/commonMain/kotlin`) and available in your common code during compilation.

CalculatorRNModuleProvider is generated in my case 

`public expect class CalculatorRNModuleProvider() : ReactNativeModuleProvider` have this there

**Comment by Samueljh1** [comment] 2023-10-31 17:22
> @Samueljh1 Were you able to resolve this? currently facing the same issue.

No, I wasn't able to unfortunately. I ended up working on a different project so stopped trying to get this to work. Please let me know if you can get this working, however.

**Comment by Legion2** [comment] 2023-11-01 21:50
Hey, can you share a reproducer project, so we can investigate the root cause of the problem. Without the full picture it's difficult to pin point the exact problem.

**Comment by Xerosigma** [comment] 2023-11-02 02:26
> Hey, can you share a reproducer project, so we can investigate the root cause of the problem. Without the full picture it's difficult to pin point the exact problem.

Also seeing this. Will try to slap something together.

**Comment by boluokvmd** [comment] 2023-11-02 15:05
> Hey, can you share a reproducer project, so we can investigate the root cause of the problem. Without the full picture it's difficult to pin point the exact problem.

I have uploaded a zipped version of the reproducer project to Drive for you to download. Here is the link: [Google Drive Link](https://drive.google.com/file/d/1TT_cnUkIE2dDX6Ty52WYRXDcre5jinWU/view?usp=sharing). Please let me know if there are any issues with accessing the file.

**Comment by Legion2** [comment] 2023-11-03 08:48
@boluokvmd thanks for the reproducer, I was able to find the missing configuration, I added `kotlin.srcDir("build/generated/ksp/metadata/commonMain/kotlin")` to kotlin > sourceSets > commonMain in the shared/build.gradle.kts. I will add this to the readme

**Comment by Legion2** [comment] 2023-11-03 08:52
You also need to remove the `kotlin.srcDir` instructions from the androidMain source set (`kotlin.srcDir("build/generated/ksp/android/androidDebug/kotlin")`), which is not needed and causes gradle task dependency issues. Then it successfully builds the project.

**Comment by boluokvmd** [comment] 2023-11-03 13:58
> @boluokvmd thanks for the reproducer, I was able to find the missing configuration, I added `kotlin.srcDir("build/generated/ksp/metadata/commonMain/kotlin")` to kotlin > sourceSets > commonMain in the shared/build.gradle.kts. I will add this to the readme

Thanks @Legion2 This solves the problem 
cc @Samueljh1

**Comment by Legion2** [comment] 2023-11-15 21:36
I'm closing this as resolved, feel free to reopen if you still have problems.

**Closed by Legion2** 2023-11-15 21:36 UTC
Labels: documentation
